### PR TITLE
Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by misteregis**
I translated it into my language, Brazilian Portuguese (pt-br).

### CODE REVIEW

**Comment by ymatuhin** [comment]
Thanks for your PR !)
I'll merge it into separate branch and then move it into master.
<3

**Comment by misteregis** [comment]
> Thanks for your PR !) I'll merge it into separate branch and then move it into master. <3

Hi, you left the lang attribute as Russian (ru) in the html tag, could you put pt-br?

image

**Comment by ymatuhin** [comment]
You're right, I'll fix it soon

**Comment by misteregis** [comment]
Yeah, I just saw it, thanks a lot for the quick reply.

Att, *Reginaldo Izidório*


Em qua., 20 de abr. de 2022 às 15:46, Yury Matuhin ***@***.***>
escreveu:

**Comment by misteregis** [comment]
Thanks!

Att, *Reginaldo Izidório*


Em qua., 20 de abr. de 2022 às 17:56, Yury Matuhin ***@***.***>
escreveu:

**Pull request merged**
